version: 0.2

run-as: root
       
phases:
  pre_build:
    run-as: root
    commands:
      - yum install python2-pip -y
      - pip install cfn-lint
      - amazon-linux-extras install ruby2.6
      - yum install ruby-devel -y
      - gem install cfn-nag
  build:
    run-as: root
    commands:
      - cfn-lint *.yaml
      - cfn_nag_scan --input-path .

#   post_build:
#     run-as: root
#     commands:
#       - command
#       - command
#     finally:
#       - command
#       - command

