version: 0.2

run-as: root
       
phases:
  pre_build:
    run-as: root
    commands:
      - yum install python2-pip amazon-linux-extras -y
      - pip install cfn-lint
      - PYTHON=python2 amazon-linux-extras install ruby2.6
      - yum install ruby-devel -y
      - gem install cfn-nag
  build:
    run-as: root
    commands:
      - cfn-lint alert.yaml sampleEC2.yaml sg.yaml
      - cfn_nag_scan --input-path sg.yaml alert.yaml sampleEC2.yaml || true

#   post_build:
#     run-as: root
#     commands:
#       - command
#       - command
#     finally:
#       - command
#       - command

